#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SiteModel;
using UDFModel;

namespace UDFModel	
{
	public partial class UDFAttachment
	{
		private int _attachmentID;
		public virtual int AttachmentID
		{
			get
			{
				return this._attachmentID;
			}
			set
			{
				this._attachmentID = value;
			}
		}
		
		private int _contentTypeID;
		public virtual int ContentTypeID
		{
			get
			{
				return this._contentTypeID;
			}
			set
			{
				this._contentTypeID = value;
			}
		}
		
		private int _uDFGroupID;
		public virtual int UDFGroupID
		{
			get
			{
				return this._uDFGroupID;
			}
			set
			{
				this._uDFGroupID = value;
			}
		}
		
		private int? _property1;
		public virtual int? ContentCategoryID
		{
			get
			{
				return this._property1;
			}
			set
			{
				this._property1 = value;
			}
		}
		
		private ContentType _contentType;
		public virtual ContentType ContentType
		{
			get
			{
				return this._contentType;
			}
			set
			{
				this._contentType = value;
			}
		}
		
		private UDFGroup _uDFGroup;
		public virtual UDFGroup UDFGroup
		{
			get
			{
				return this._uDFGroup;
			}
			set
			{
				this._uDFGroup = value;
			}
		}
		
	}
}
#pragma warning restore 1591
