#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using GeoModel;

namespace GeoModel	
{
	public partial class Ref_city
	{
		private string _province_Cd;
		public virtual string Province_cd
		{
			get
			{
				return this._province_Cd;
			}
			set
			{
				this._province_Cd = value;
			}
		}
		
		private string _city_Name;
		public virtual string City_name
		{
			get
			{
				return this._city_Name;
			}
			set
			{
				this._city_Name = value;
			}
		}
		
		private int _city_Id;
		public virtual int City_id
		{
			get
			{
				return this._city_Id;
			}
			set
			{
				this._city_Id = value;
			}
		}
		
		private Ref_province _ref_Province;
		public virtual Ref_province Ref_province
		{
			get
			{
				return this._ref_Province;
			}
			set
			{
				this._ref_Province = value;
			}
		}
		
		private IList<Ref_postalcode> _ref_Postalcodes = new List<Ref_postalcode>();
		public virtual IList<Ref_postalcode> Ref_postalcodes
		{
			get
			{
				return this._ref_Postalcodes;
			}
		}
		
	}
}
#pragma warning restore 1591
