#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SiteModel	
{
	public partial class CustomPage
	{
		private int _customPageId;
		public virtual int CustomPageId
		{
			get
			{
				return this._customPageId;
			}
			set
			{
				this._customPageId = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private string _metadataStr;
		public virtual string MetadataStr
		{
			get
			{
				return this._metadataStr;
			}
			set
			{
				this._metadataStr = value;
			}
		}
		
		private bool _deletedFg;
		public virtual bool DeletedFg
		{
			get
			{
				return this._deletedFg;
			}
			set
			{
				this._deletedFg = value;
			}
		}
		
		private string _pageTitle;
		public virtual string PageTitle
		{
			get
			{
				return this._pageTitle;
			}
			set
			{
				this._pageTitle = value;
			}
		}
		
		private string _metaDescription;
		public virtual string MetaDescription
		{
			get
			{
				return this._metaDescription;
			}
			set
			{
				this._metaDescription = value;
			}
		}
		
	}
}
#pragma warning restore 1591
