#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SiteModel	
{
	public partial class SearchQuery
	{
		private string _query;
		public virtual string Query
		{
			get
			{
				return this._query;
			}
			set
			{
				this._query = value;
			}
		}
		
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private DateTime _queryDate;
		public virtual DateTime QueryDate
		{
			get
			{
				return this._queryDate;
			}
			set
			{
				this._queryDate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
