#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using UserModel;

namespace UserModel	
{
	public partial class Users
	{
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private Guid _userId;
		public virtual Guid UserId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		
		private string _mobileAlias;
		public virtual string MobileAlias
		{
			get
			{
				return this._mobileAlias;
			}
			set
			{
				this._mobileAlias = value;
			}
		}
		
		private string _loweredUserName;
		public virtual string LoweredUserName
		{
			get
			{
				return this._loweredUserName;
			}
			set
			{
				this._loweredUserName = value;
			}
		}
		
		private DateTime _lastActivityDate;
		public virtual DateTime LastActivityDate
		{
			get
			{
				return this._lastActivityDate;
			}
			set
			{
				this._lastActivityDate = value;
			}
		}
		
		private bool _isAnonymous;
		public virtual bool IsAnonymous
		{
			get
			{
				return this._isAnonymous;
			}
			set
			{
				this._isAnonymous = value;
			}
		}
		
		private Guid _applicationId;
		public virtual Guid ApplicationId
		{
			get
			{
				return this._applicationId;
			}
			set
			{
				this._applicationId = value;
			}
		}
		
		private Application _aspnet_Application;
		public virtual Application Aspnet_Application
		{
			get
			{
				return this._aspnet_Application;
			}
			set
			{
				this._aspnet_Application = value;
			}
		}
		
		private UserMembership _userMembership;
		public virtual UserMembership UserMembership
		{
			get
			{
				return this._userMembership;
			}
			set
			{
				this._userMembership = value;
			}
		}
		
		private IList<UserRoleMembership> _aspnet_UsersInRoles = new List<UserRoleMembership>();
		public virtual IList<UserRoleMembership> Aspnet_UsersInRoles
		{
			get
			{
				return this._aspnet_UsersInRoles;
			}
		}
		
		private IList<UserLink> _userLinks = new List<UserLink>();
		public virtual IList<UserLink> UserLinks
		{
			get
			{
				return this._userLinks;
			}
		}
		
		private UserProfile _aspnet_Profiles;
		public virtual UserProfile Aspnet_Profiles
		{
			get
			{
				return this._aspnet_Profiles;
			}
			set
			{
				this._aspnet_Profiles = value;
			}
		}
		
	}
}
#pragma warning restore 1591
