#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using UserModel;

namespace UserModel	
{
	public partial class UserMembership
	{
		private Guid _userId;
		public virtual Guid UserId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		
		private string _passwordSalt;
		public virtual string PasswordSalt
		{
			get
			{
				return this._passwordSalt;
			}
			set
			{
				this._passwordSalt = value;
			}
		}
		
		private string _passwordQuestion;
		public virtual string PasswordQuestion
		{
			get
			{
				return this._passwordQuestion;
			}
			set
			{
				this._passwordQuestion = value;
			}
		}
		
		private int _passwordFormat;
		public virtual int PasswordFormat
		{
			get
			{
				return this._passwordFormat;
			}
			set
			{
				this._passwordFormat = value;
			}
		}
		
		private string _passwordAnswer;
		public virtual string PasswordAnswer
		{
			get
			{
				return this._passwordAnswer;
			}
			set
			{
				this._passwordAnswer = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _mobilePIN;
		public virtual string MobilePIN
		{
			get
			{
				return this._mobilePIN;
			}
			set
			{
				this._mobilePIN = value;
			}
		}
		
		private string _loweredEmail;
		public virtual string LoweredEmail
		{
			get
			{
				return this._loweredEmail;
			}
			set
			{
				this._loweredEmail = value;
			}
		}
		
		private DateTime _lastPasswordChangedDate;
		public virtual DateTime LastPasswordChangedDate
		{
			get
			{
				return this._lastPasswordChangedDate;
			}
			set
			{
				this._lastPasswordChangedDate = value;
			}
		}
		
		private DateTime _lastLoginDate;
		public virtual DateTime LastLoginDate
		{
			get
			{
				return this._lastLoginDate;
			}
			set
			{
				this._lastLoginDate = value;
			}
		}
		
		private DateTime _lastLockoutDate;
		public virtual DateTime LastLockoutDate
		{
			get
			{
				return this._lastLockoutDate;
			}
			set
			{
				this._lastLockoutDate = value;
			}
		}
		
		private bool _isLockedOut;
		public virtual bool IsLockedOut
		{
			get
			{
				return this._isLockedOut;
			}
			set
			{
				this._isLockedOut = value;
			}
		}
		
		private bool _isApproved;
		public virtual bool IsApproved
		{
			get
			{
				return this._isApproved;
			}
			set
			{
				this._isApproved = value;
			}
		}
		
		private DateTime _failedPasswordAttemptWindowStart;
		public virtual DateTime FailedPasswordAttemptWindowStart
		{
			get
			{
				return this._failedPasswordAttemptWindowStart;
			}
			set
			{
				this._failedPasswordAttemptWindowStart = value;
			}
		}
		
		private int _failedPasswordAttemptCount;
		public virtual int FailedPasswordAttemptCount
		{
			get
			{
				return this._failedPasswordAttemptCount;
			}
			set
			{
				this._failedPasswordAttemptCount = value;
			}
		}
		
		private DateTime _failedPasswordAnswerAttemptWindowStart;
		public virtual DateTime FailedPasswordAnswerAttemptWindowStart
		{
			get
			{
				return this._failedPasswordAnswerAttemptWindowStart;
			}
			set
			{
				this._failedPasswordAnswerAttemptWindowStart = value;
			}
		}
		
		private int _failedPasswordAnswerAttemptCount;
		public virtual int FailedPasswordAnswerAttemptCount
		{
			get
			{
				return this._failedPasswordAnswerAttemptCount;
			}
			set
			{
				this._failedPasswordAnswerAttemptCount = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private string _comment;
		public virtual string Comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				this._comment = value;
			}
		}
		
		private Guid _applicationId;
		public virtual Guid ApplicationId
		{
			get
			{
				return this._applicationId;
			}
			set
			{
				this._applicationId = value;
			}
		}
		
		private Application _aspnet_Application;
		public virtual Application Aspnet_Application
		{
			get
			{
				return this._aspnet_Application;
			}
			set
			{
				this._aspnet_Application = value;
			}
		}
		
		private IList<Users> _users = new List<Users>();
		public virtual IList<Users> Users
		{
			get
			{
				return this._users;
			}
		}
		
	}
}
#pragma warning restore 1591
