#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using UserModel;

namespace UserModel	
{
	public partial class UserRoles
	{
		private string _roleName;
		public virtual string RoleName
		{
			get
			{
				return this._roleName;
			}
			set
			{
				this._roleName = value;
			}
		}
		
		private Guid _roleId;
		public virtual Guid RoleId
		{
			get
			{
				return this._roleId;
			}
			set
			{
				this._roleId = value;
			}
		}
		
		private string _loweredRoleName;
		public virtual string LoweredRoleName
		{
			get
			{
				return this._loweredRoleName;
			}
			set
			{
				this._loweredRoleName = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private Guid _applicationId;
		public virtual Guid ApplicationId
		{
			get
			{
				return this._applicationId;
			}
			set
			{
				this._applicationId = value;
			}
		}
		
		private Application _aspnet_Application;
		public virtual Application Aspnet_Application
		{
			get
			{
				return this._aspnet_Application;
			}
			set
			{
				this._aspnet_Application = value;
			}
		}
		
		private IList<UserRoleMembership> _aspnet_UsersInRoles = new List<UserRoleMembership>();
		public virtual IList<UserRoleMembership> Aspnet_UsersInRoles
		{
			get
			{
				return this._aspnet_UsersInRoles;
			}
		}
		
	}
}
#pragma warning restore 1591
