#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using UserModel;

namespace UserModel	
{
	public partial class UserProfile
	{
		private Guid _userId;
		public virtual Guid UserId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		
		private string _propertyValuesString;
		public virtual string PropertyValuesString
		{
			get
			{
				return this._propertyValuesString;
			}
			set
			{
				this._propertyValuesString = value;
			}
		}
		
		private byte[] _propertyValuesBinary;
		public virtual byte[] PropertyValuesBinary
		{
			get
			{
				return this._propertyValuesBinary;
			}
			set
			{
				this._propertyValuesBinary = value;
			}
		}
		
		private string _propertyNames;
		public virtual string PropertyNames
		{
			get
			{
				return this._propertyNames;
			}
			set
			{
				this._propertyNames = value;
			}
		}
		
		private DateTime _lastUpdatedDate;
		public virtual DateTime LastUpdatedDate
		{
			get
			{
				return this._lastUpdatedDate;
			}
			set
			{
				this._lastUpdatedDate = value;
			}
		}
		
		private Users _aspnet_User;
		public virtual Users Aspnet_User
		{
			get
			{
				return this._aspnet_User;
			}
			set
			{
				this._aspnet_User = value;
			}
		}
		
	}
}
#pragma warning restore 1591
