#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ArticleModel;

namespace ArticleModel	
{
	public partial class ArticleCategory
	{
		private int _artCatId;
		public virtual int ArtCatId
		{
			get
			{
				return this._artCatId;
			}
			set
			{
				this._artCatId = value;
			}
		}
		
		private string _catName;
		public virtual string CatName
		{
			get
			{
				return this._catName;
			}
			set
			{
				this._catName = value;
			}
		}
		
		private bool _linkArticleFg;
		public virtual bool LinkArticle_fg
		{
			get
			{
				return this._linkArticleFg;
			}
			set
			{
				this._linkArticleFg = value;
			}
		}
		
		private string _metadataStr;
		public virtual string metadataStr
		{
			get
			{
				return this._metadataStr;
			}
			set
			{
				this._metadataStr = value;
			}
		}
		
		private bool _virtualCat_Fg;
		public virtual bool VirtualCat_fg
		{
			get
			{
				return this._virtualCat_Fg;
			}
			set
			{
				this._virtualCat_Fg = value;
			}
		}
		
		private string _detailMetadataStr;
		public virtual string DetailMetadataStr
		{
			get
			{
				return this._detailMetadataStr;
			}
			set
			{
				this._detailMetadataStr = value;
			}
		}
		
		private bool _deleted_fg;
		public virtual bool Deleted_fg
		{
			get
			{
				return this._deleted_fg;
			}
			set
			{
				this._deleted_fg = value;
			}
		}
		
		private string _urlSlug;
		public virtual string UrlSlug
		{
			get
			{
				return this._urlSlug;
			}
			set
			{
				this._urlSlug = value;
			}
		}
		
		private IList<Article> _articles1 = new List<Article>();
		public virtual IList<Article> Articles1
		{
			get
			{
				return this._articles1;
			}
		}
		
		private IList<VirtualCategoryLink> _virtualCategoryLinks = new List<VirtualCategoryLink>();
		public virtual IList<VirtualCategoryLink> VirtualCategoryLinks
		{
			get
			{
				return this._virtualCategoryLinks;
			}
		}
		
	}
}
#pragma warning restore 1591
