#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ArticleModel;

namespace ArticleModel	
{
	public partial class ArticleComment
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _articleId;
		public virtual int ArticleId
		{
			get
			{
				return this._articleId;
			}
			set
			{
				this._articleId = value;
			}
		}
		
		private string _subject;
		public virtual string Subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				this._subject = value;
			}
		}
		
		private string _comment;
		public virtual string Comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				this._comment = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _postBy;
		public virtual string PostBy
		{
			get
			{
				return this._postBy;
			}
			set
			{
				this._postBy = value;
			}
		}
		
		private DateTime _postDate;
		public virtual DateTime PostDate
		{
			get
			{
				return this._postDate;
			}
			set
			{
				this._postDate = value;
			}
		}
		
		private string _iPAddr;
		public virtual string IPAddr
		{
			get
			{
				return this._iPAddr;
			}
			set
			{
				this._iPAddr = value;
			}
		}
		
		private bool _removed;
		public virtual bool Removed
		{
			get
			{
				return this._removed;
			}
			set
			{
				this._removed = value;
			}
		}
		
		private bool _blocked;
		public virtual bool Blocked
		{
			get
			{
				return this._blocked;
			}
			set
			{
				this._blocked = value;
			}
		}
		
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private Article _article;
		public virtual Article Article
		{
			get
			{
				return this._article;
			}
			set
			{
				this._article = value;
			}
		}
		
	}
}
#pragma warning restore 1591
