#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ArticleModel;

namespace ArticleModel	
{
	public partial class RelatedArticle
	{
		private int _articleId;
		public virtual int ArticleId
		{
			get
			{
				return this._articleId;
			}
			set
			{
				this._articleId = value;
			}
		}
		
		private int _relatedArticleId;
		public virtual int RelatedArticleId
		{
			get
			{
				return this._relatedArticleId;
			}
			set
			{
				this._relatedArticleId = value;
			}
		}
		
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private Article _article;
		public virtual Article Article
		{
			get
			{
				return this._article;
			}
			set
			{
				this._article = value;
			}
		}
		
	}
}
#pragma warning restore 1591
