#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SiteModel;
using BizModel;

namespace BizModel	
{
	public partial class BusinessEntityThumbnail
	{
		private int _bizThumbId;
		public virtual int BizThumbId
		{
			get
			{
				return this._bizThumbId;
			}
			set
			{
				this._bizThumbId = value;
			}
		}
		
		private int _businessEntityImageId;
		public virtual int BusinessEntityImageId
		{
			get
			{
				return this._businessEntityImageId;
			}
			set
			{
				this._businessEntityImageId = value;
			}
		}
		
		private int _thumbnailTypeId;
		public virtual int ThumbnailTypeId
		{
			get
			{
				return this._thumbnailTypeId;
			}
			set
			{
				this._thumbnailTypeId = value;
			}
		}
		
		private string _thumbnailPath;
		public virtual string ThumbnailPath
		{
			get
			{
				return this._thumbnailPath;
			}
			set
			{
				this._thumbnailPath = value;
			}
		}
		
		private ThumbnailType _thumbnailType;
		public virtual ThumbnailType ThumbnailType
		{
			get
			{
				return this._thumbnailType;
			}
			set
			{
				this._thumbnailType = value;
			}
		}
		
		private BusinessEntityImage _businessEntityImage;
		public virtual BusinessEntityImage BusinessEntityImage
		{
			get
			{
				return this._businessEntityImage;
			}
			set
			{
				this._businessEntityImage = value;
			}
		}
		
	}
}
#pragma warning restore 1591
