#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using ForumModel;

namespace ForumModel	
{
	public partial class ForumThread
	{
		private int _viewCount;
		public virtual int ViewCount
		{
			get
			{
				return this._viewCount;
			}
			set
			{
				this._viewCount = value;
			}
		}
		
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private string _thumb;
		public virtual string Thumb
		{
			get
			{
				return this._thumb;
			}
			set
			{
				this._thumb = value;
			}
		}
		
		private int _threadNum;
		public virtual int ThreadNum
		{
			get
			{
				return this._threadNum;
			}
			set
			{
				this._threadNum = value;
			}
		}
		
		private int _threadId;
		public virtual int ThreadId
		{
			get
			{
				return this._threadId;
			}
			set
			{
				this._threadId = value;
			}
		}
		
		private bool _suspended;
		public virtual bool Suspended
		{
			get
			{
				return this._suspended;
			}
			set
			{
				this._suspended = value;
			}
		}
		
		private string _subject;
		public virtual string Subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				this._subject = value;
			}
		}
		
		private bool _private;
		public virtual bool Private
		{
			get
			{
				return this._private;
			}
			set
			{
				this._private = value;
			}
		}
		
		private DateTime _postDate;
		public virtual DateTime PostDate
		{
			get
			{
				return this._postDate;
			}
			set
			{
				this._postDate = value;
			}
		}
		
		private string _postBy;
		public virtual string PostBy
		{
			get
			{
				return this._postBy;
			}
			set
			{
				this._postBy = value;
			}
		}
		
		private string _password;
		public virtual string Password
		{
			get
			{
				return this._password;
			}
			set
			{
				this._password = value;
			}
		}
		
		private string _iPAddress;
		public virtual string IPAddress
		{
			get
			{
				return this._iPAddress;
			}
			set
			{
				this._iPAddress = value;
			}
		}
		
		private int _forumId;
		public virtual int ForumId
		{
			get
			{
				return this._forumId;
			}
			set
			{
				this._forumId = value;
			}
		}
		
		private string _body;
		public virtual string Body
		{
			get
			{
				return this._body;
			}
			set
			{
				this._body = value;
			}
		}
		
		private bool _announce;
		public virtual bool Announce
		{
			get
			{
				return this._announce;
			}
			set
			{
				this._announce = value;
			}
		}
		
		private Forum _forum;
		public virtual Forum Forum
		{
			get
			{
				return this._forum;
			}
			set
			{
				this._forum = value;
			}
		}
		
		private IList<ForumComment> _forumComments = new List<ForumComment>();
		public virtual IList<ForumComment> ForumComments
		{
			get
			{
				return this._forumComments;
			}
		}
		
		private IList<ForumAttachments> _forumAttachments = new List<ForumAttachments>();
		public virtual IList<ForumAttachments> ForumAttachments
		{
			get
			{
				return this._forumAttachments;
			}
		}
		
	}
}
#pragma warning restore 1591
