//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Account_btn_RegSubmit {
            get {
                return ResourceManager.GetString("Account.btn_RegSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Your Account.
        /// </summary>
        internal static string Account_email_AccountRegEmailSubject {
            get {
                return ResourceManager.GetString("Account.email_AccountRegEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        internal static string Account_email_PasswordReset {
            get {
                return ResourceManager.GetString("Account.email_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        internal static string Account_lbl_Address1 {
            get {
                return ResourceManager.GetString("Account.lbl_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        internal static string Account_lbl_Address2 {
            get {
                return ResourceManager.GetString("Account.lbl_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Account_lbl_City {
            get {
                return ResourceManager.GetString("Account.lbl_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Account_lbl_Comment {
            get {
                return ResourceManager.GetString("Account.lbl_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Account_lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account.lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string Account_lbl_CurrentPassword {
            get {
                return ResourceManager.GetString("Account.lbl_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Account_lbl_EmailAddress {
            get {
                return ResourceManager.GetString("Account.lbl_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address does not exist.
        /// </summary>
        internal static string Account_lbl_EmailConfirmFail {
            get {
                return ResourceManager.GetString("Account.lbl_EmailConfirmFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with your username has been successfully sent to you. .
        /// </summary>
        internal static string Account_lbl_EmailConfirmSuccess {
            get {
                return ResourceManager.GetString("Account.lbl_EmailConfirmSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Me.
        /// </summary>
        internal static string Account_lbl_EmailMe {
            get {
                return ResourceManager.GetString("Account.lbl_EmailMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        internal static string Account_lbl_EnterEmailAddress {
            get {
                return ResourceManager.GetString("Account.lbl_EnterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address again..
        /// </summary>
        internal static string Account_lbl_EnterEmailAgain {
            get {
                return ResourceManager.GetString("Account.lbl_EnterEmailAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLease enter password again..
        /// </summary>
        internal static string Account_lbl_EnterPasswordAgain {
            get {
                return ResourceManager.GetString("Account.lbl_EnterPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        internal static string Account_lbl_FaxNumber {
            get {
                return ResourceManager.GetString("Account.lbl_FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Password?.
        /// </summary>
        internal static string Account_lbl_FindPassword {
            get {
                return ResourceManager.GetString("Account.lbl_FindPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user name and email address you singed up with. We will email you with the instruction to reset your password..
        /// </summary>
        internal static string Account_lbl_FindPasswordDescr {
            get {
                return ResourceManager.GetString("Account.lbl_FindPasswordDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Your Username?.
        /// </summary>
        internal static string Account_lbl_FindUserName {
            get {
                return ResourceManager.GetString("Account.lbl_FindUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us the email address you singed up with. We will email you with your username..
        /// </summary>
        internal static string Account_lbl_FindUserNameDescr {
            get {
                return ResourceManager.GetString("Account.lbl_FindUserNameDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Username / Password.
        /// </summary>
        internal static string Account_lbl_FindUserNamePassword {
            get {
                return ResourceManager.GetString("Account.lbl_FindUserNamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish User Registration.
        /// </summary>
        internal static string Account_lbl_FinishRegistration {
            get {
                return ResourceManager.GetString("Account.lbl_FinishRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Account_lbl_FirstName {
            get {
                return ResourceManager.GetString("Account.lbl_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Login Page.
        /// </summary>
        internal static string Account_lbl_GoToLoginPage {
            get {
                return ResourceManager.GetString("Account.lbl_GoToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Account_lbl_LastName {
            get {
                return ResourceManager.GetString("Account.lbl_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string Account_lbl_NewPassword {
            get {
                return ResourceManager.GetString("Account.lbl_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional User Profile.
        /// </summary>
        internal static string Account_lbl_OptionalInfo {
            get {
                return ResourceManager.GetString("Account.lbl_OptionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Account_lbl_PhoneNumber {
            get {
                return ResourceManager.GetString("Account.lbl_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Required Fields.
        /// </summary>
        internal static string Account_lbl_RequiredField {
            get {
                return ResourceManager.GetString("Account.lbl_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required User Profile.
        /// </summary>
        internal static string Account_lbl_RequiredInfo {
            get {
                return ResourceManager.GetString("Account.lbl_RequiredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Account_lbl_ResetPassword {
            get {
                return ResourceManager.GetString("Account.lbl_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / Province.
        /// </summary>
        internal static string Account_lbl_State {
            get {
                return ResourceManager.GetString("Account.lbl_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        internal static string Account_lbl_UpdatePassword {
            get {
                return ResourceManager.GetString("Account.lbl_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update My Profile.
        /// </summary>
        internal static string Account_lbl_UpdateProfile {
            get {
                return ResourceManager.GetString("Account.lbl_UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        internal static string Account_lbl_UserReg {
            get {
                return ResourceManager.GetString("Account.lbl_UserReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format. Please enter your email address again..
        /// </summary>
        internal static string Account_lbl_WrongEmailFormat {
            get {
                return ResourceManager.GetString("Account.lbl_WrongEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip / Postal Code.
        /// </summary>
        internal static string Account_lbl_ZipCode {
            get {
                return ResourceManager.GetString("Account.lbl_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account has been created. Activate your account now!!.
        /// </summary>
        internal static string Account_msg_AccountRegEmailSubject {
            get {
                return ResourceManager.GetString("Account.msg_AccountRegEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account has been successfully created. \n The instruction to activate your account has been sent to your email. Please check your email and follow the instruction..
        /// </summary>
        internal static string Account_msg_AccountRegSuccess {
            get {
                return ResourceManager.GetString("Account.msg_AccountRegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! We are not able to activate your account..
        /// </summary>
        internal static string Account_msg_AccountVerifyFail1 {
            get {
                return ResourceManager.GetString("Account.msg_AccountVerifyFail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the email account you singed up with. &lt;br/&gt;In order to finish user registration, you need to follow the instruction in the email sent out to your email account when you signed up..
        /// </summary>
        internal static string Account_msg_AccountVerifyFail2 {
            get {
                return ResourceManager.GetString("Account.msg_AccountVerifyFail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for creating a user account. .
        /// </summary>
        internal static string Account_msg_AccountVerifySuccess1 {
            get {
                return ResourceManager.GetString("Account.msg_AccountVerifySuccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been successfully activated..
        /// </summary>
        internal static string Account_msg_AccountVerifySuccess2 {
            get {
                return ResourceManager.GetString("Account.msg_AccountVerifySuccess2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Account_msg_Available {
            get {
                return ResourceManager.GetString("Account.msg_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is already registered.
        /// </summary>
        internal static string Account_msg_EmailExists {
            get {
                return ResourceManager.GetString("Account.msg_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email addresses do not match.
        /// </summary>
        internal static string Account_msg_EmailMatch {
            get {
                return ResourceManager.GetString("Account.msg_EmailMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email address.
        /// </summary>
        internal static string Account_msg_EmailReq {
            get {
                return ResourceManager.GetString("Account.msg_EmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format. Please enter your email again..
        /// </summary>
        internal static string Account_msg_EmailValidation {
            get {
                return ResourceManager.GetString("Account.msg_EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name.
        /// </summary>
        internal static string Account_msg_FirstNameReq {
            get {
                return ResourceManager.GetString("Account.msg_FirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name.
        /// </summary>
        internal static string Account_msg_LastNameReq {
            get {
                return ResourceManager.GetString("Account.msg_LastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already In Use.
        /// </summary>
        internal static string Account_msg_NotAvailable {
            get {
                return ResourceManager.GetString("Account.msg_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string Account_msg_PasswordMatch {
            get {
                return ResourceManager.GetString("Account.msg_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        internal static string Account_msg_PasswordReq {
            get {
                return ResourceManager.GetString("Account.msg_PasswordReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password has been sent to your email address..
        /// </summary>
        internal static string Account_msg_PasswordSent {
            get {
                return ResourceManager.GetString("Account.msg_PasswordSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be more than 6 characters..
        /// </summary>
        internal static string Account_msg_PasswordValidation {
            get {
                return ResourceManager.GetString("Account.msg_PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. we are not able to email you the requested information due to unexpected error. Please contact the website administrator..
        /// </summary>
        internal static string Account_msg_ProblemOccured {
            get {
                return ResourceManager.GetString("Account.msg_ProblemOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is not allowed.
        /// </summary>
        internal static string Account_msg_UserNameNotAllowed {
            get {
                return ResourceManager.GetString("Account.msg_UserNameNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter UserName.
        /// </summary>
        internal static string Account_msg_UserNameReq {
            get {
                return ResourceManager.GetString("Account.msg_UserNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be 4-16 alphabetic characters or numbers.
        /// </summary>
        internal static string Account_msg_UserNameValidation {
            get {
                return ResourceManager.GetString("Account.msg_UserNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, We are not able to find your username and email address..
        /// </summary>
        internal static string Account_msg_UserNotRegistered {
            get {
                return ResourceManager.GetString("Account.msg_UserNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To protect your information, please enter your password again..
        /// </summary>
        internal static string Account_msg_VarifyPassword {
            get {
                return ResourceManager.GetString("Account.msg_VarifyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        internal static string Account_msg_WrongPassword {
            get {
                return ResourceManager.GetString("Account.msg_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Availability.
        /// </summary>
        internal static string Acount_lbl_UserNameAvail {
            get {
                return ResourceManager.GetString("Acount.lbl_UserNameAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string Admin_lbl_UpdatePassword {
            get {
                return ResourceManager.GetString("Admin.lbl_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Article_lbl_Cancel {
            get {
                return ResourceManager.GetString("Article.lbl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Category.
        /// </summary>
        internal static string Article_lbl_Category {
            get {
                return ResourceManager.GetString("Article.lbl_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents Editor.
        /// </summary>
        internal static string Article_lbl_ContentEditor {
            get {
                return ResourceManager.GetString("Article.lbl_ContentEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click an image to insert into the editor..
        /// </summary>
        internal static string Article_lbl_ImageClick {
            get {
                return ResourceManager.GetString("Article.lbl_ImageClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Date/Time.
        /// </summary>
        internal static string Article_lbl_IssueDateTime {
            get {
                return ResourceManager.GetString("Article.lbl_IssueDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum image file size: .
        /// </summary>
        internal static string Article_lbl_MaxImageSize {
            get {
                return ResourceManager.GetString("Article.lbl_MaxImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Virtual Category Available.
        /// </summary>
        internal static string Article_lbl_NoVirCatAvail {
            get {
                return ResourceManager.GetString("Article.lbl_NoVirCatAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Article.
        /// </summary>
        internal static string Article_lbl_Post {
            get {
                return ResourceManager.GetString("Article.lbl_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted By.
        /// </summary>
        internal static string Article_lbl_PostedBy {
            get {
                return ResourceManager.GetString("Article.lbl_PostedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Articles.
        /// </summary>
        internal static string Article_lbl_RelatedArticles {
            get {
                return ResourceManager.GetString("Article.lbl_RelatedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Article_lbl_Save {
            get {
                return ResourceManager.GetString("Article.lbl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Article_lbl_Search {
            get {
                return ResourceManager.GetString("Article.lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Category.
        /// </summary>
        internal static string Article_lbl_SecondaryCategory {
            get {
                return ResourceManager.GetString("Article.lbl_SecondaryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Virtual Category.
        /// </summary>
        internal static string Article_lbl_SelectVirCat {
            get {
                return ResourceManager.GetString("Article.lbl_SelectVirCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Title.
        /// </summary>
        internal static string Article_lbl_SubTitle {
            get {
                return ResourceManager.GetString("Article.lbl_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Article_lbl_Tags {
            get {
                return ResourceManager.GetString("Article.lbl_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Article_lbl_Title {
            get {
                return ResourceManager.GetString("Article.lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Thumbnail.
        /// </summary>
        internal static string Article_lbl_UpdateThumbnail {
            get {
                return ResourceManager.GetString("Article.lbl_UpdateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, The thumbnail update page will show after article is saved..
        /// </summary>
        internal static string Article_lbl_UpdateThumbnailDescr {
            get {
                return ResourceManager.GetString("Article.lbl_UpdateThumbnailDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Images.
        /// </summary>
        internal static string Article_lbl_UploadImages {
            get {
                return ResourceManager.GetString("Article.lbl_UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Article_lbl_Views {
            get {
                return ResourceManager.GetString("Article.lbl_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string Article_msg_PostRequiredField {
            get {
                return ResourceManager.GetString("Article.msg_PostRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article has been successfully submitted.
        /// </summary>
        internal static string Article_msg_PostSuccess {
            get {
                return ResourceManager.GetString("Article.msg_PostSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image upload failed due to invalid format or/and size:.
        /// </summary>
        internal static string Article_msg_UploadImage {
            get {
                return ResourceManager.GetString("Article.msg_UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code you entered is not valid..
        /// </summary>
        internal static string Captcha_ErrorMassage {
            get {
                return ResourceManager.GetString("Captcha.ErrorMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the code from the image.
        /// </summary>
        internal static string Captcha_TypeCode {
            get {
                return ResourceManager.GetString("Captcha.TypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string Classified_lbl_AdNumber {
            get {
                return ResourceManager.GetString("Classified.lbl_AdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Classified_lbl_Date {
            get {
                return ResourceManager.GetString("Classified.lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Classified_lbl_Name {
            get {
                return ResourceManager.GetString("Classified.lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Classified_lbl_Notice {
            get {
                return ResourceManager.GetString("Classified.lbl_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Classified_lbl_Search {
            get {
                return ResourceManager.GetString("Classified.lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Classified_lbl_Title {
            get {
                return ResourceManager.GetString("Classified.lbl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Classified_lbl_View {
            get {
                return ResourceManager.GetString("Classified.lbl_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse File(s)....
        /// </summary>
        internal static string Forum_btn_Attachments {
            get {
                return ResourceManager.GetString("Forum.btn_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        internal static string Forum_lbl_Announcement {
            get {
                return ResourceManager.GetString("Forum.lbl_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if it is an annoucement post.
        /// </summary>
        internal static string Forum_lbl_AnnouncementCheck {
            get {
                return ResourceManager.GetString("Forum.lbl_AnnouncementCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if you would like to delete the existing attachment(s).
        /// </summary>
        internal static string Forum_lbl_AttachmentDelete {
            get {
                return ResourceManager.GetString("Forum.lbl_AttachmentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment(s).
        /// </summary>
        internal static string Forum_lbl_Attachments {
            get {
                return ResourceManager.GetString("Forum.lbl_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Forum_lbl_Captcha {
            get {
                return ResourceManager.GetString("Forum.lbl_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 4 digits displayed on the right..
        /// </summary>
        internal static string Forum_lbl_CaptchaMsg {
            get {
                return ResourceManager.GetString("Forum.lbl_CaptchaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Forum_lbl_Content {
            get {
                return ResourceManager.GetString("Forum.lbl_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Forum_lbl_Date {
            get {
                return ResourceManager.GetString("Forum.lbl_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Forum_lbl_Name {
            get {
                return ResourceManager.GetString("Forum.lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Thread.
        /// </summary>
        internal static string Forum_lbl_NewThread {
            get {
                return ResourceManager.GetString("Forum.lbl_NewThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Forum_lbl_Number {
            get {
                return ResourceManager.GetString("Forum.lbl_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Forum_lbl_Password {
            get {
                return ResourceManager.GetString("Forum.lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The thread password is required to open this private thread..
        /// </summary>
        internal static string Forum_lbl_PasswordEnter {
            get {
                return ResourceManager.GetString("Forum.lbl_PasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for editing and deleting the thread. Maxumum 8 characters..
        /// </summary>
        internal static string Forum_lbl_PasswordMsg {
            get {
                return ResourceManager.GetString("Forum.lbl_PasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Forum_lbl_Private {
            get {
                return ResourceManager.GetString("Forum.lbl_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check if it is a private post. (The post will be locked by the password entered below.).
        /// </summary>
        internal static string Forum_lbl_PrivateCheck {
            get {
                return ResourceManager.GetString("Forum.lbl_PrivateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Forum_lbl_RequiredField {
            get {
                return ResourceManager.GetString("Forum.lbl_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Forum_lbl_Subject {
            get {
                return ResourceManager.GetString("Forum.lbl_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string Forum_lbl_Views {
            get {
                return ResourceManager.GetString("Forum.lbl_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Forum_lbl_Writer {
            get {
                return ResourceManager.GetString("Forum.lbl_Writer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid attachment(s).
        /// </summary>
        internal static string Forum_msg_Attachments {
            get {
                return ResourceManager.GetString("Forum.msg_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the thread password..
        /// </summary>
        internal static string Forum_msg_PasswordEnter {
            get {
                return ResourceManager.GetString("Forum.msg_PasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please contact system administrator for further assistance..
        /// </summary>
        internal static string Gen_ErrorOccurContactAdmin {
            get {
                return ResourceManager.GetString("Gen.ErrorOccurContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Gen_lbl_Add {
            get {
                return ResourceManager.GetString("Gen.lbl_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Gen_lbl_Cancel {
            get {
                return ResourceManager.GetString("Gen.lbl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Gen_lbl_count {
            get {
                return ResourceManager.GetString("Gen.lbl_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Gen_lbl_Delete {
            get {
                return ResourceManager.GetString("Gen.lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Gen_lbl_Edit {
            get {
                return ResourceManager.GetString("Gen.lbl_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g..
        /// </summary>
        internal static string Gen_lbl_Example {
            get {
                return ResourceManager.GetString("Gen.lbl_Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string Gen_lbl_List {
            get {
                return ResourceManager.GetString("Gen.lbl_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string Gen_lbl_Move {
            get {
                return ResourceManager.GetString("Gen.lbl_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Gen_lbl_Next {
            get {
                return ResourceManager.GetString("Gen.lbl_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Gen_lbl_Ok {
            get {
                return ResourceManager.GetString("Gen.lbl_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select --.
        /// </summary>
        internal static string Gen_lbl_OptionSelect {
            get {
                return ResourceManager.GetString("Gen.lbl_OptionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string Gen_lbl_Post {
            get {
                return ResourceManager.GetString("Gen.lbl_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string Gen_lbl_Previous {
            get {
                return ResourceManager.GetString("Gen.lbl_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Gen_lbl_Search {
            get {
                return ResourceManager.GetString("Gen.lbl_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Gen_lbl_Send {
            get {
                return ResourceManager.GetString("Gen.lbl_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Gen_lbl_Submit {
            get {
                return ResourceManager.GetString("Gen.lbl_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string Login_btn_login {
            get {
                return ResourceManager.GetString("Login.btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Me Signin.
        /// </summary>
        internal static string Login_ChkKeepMeSignIn {
            get {
                return ResourceManager.GetString("Login.ChkKeepMeSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        internal static string Login_ChkRememberMe {
            get {
                return ResourceManager.GetString("Login.ChkRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Username or Password .
        /// </summary>
        internal static string Login_FailMassage {
            get {
                return ResourceManager.GetString("Login.FailMassage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Login_lbl_login {
            get {
                return ResourceManager.GetString("Login.lbl_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Login_lbl_logout {
            get {
                return ResourceManager.GetString("Login.lbl_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string Login_lbl_LostPassword {
            get {
                return ResourceManager.GetString("Login.lbl_LostPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Username.
        /// </summary>
        internal static string Login_lbl_LostUserName {
            get {
                return ResourceManager.GetString("Login.lbl_LostUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Login_lbl_MyProfile {
            get {
                return ResourceManager.GetString("Login.lbl_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_lbl_Password {
            get {
                return ResourceManager.GetString("Login.lbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Login_lbl_signup {
            get {
                return ResourceManager.GetString("Login.lbl_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Login_lbl_Userinfo {
            get {
                return ResourceManager.GetString("Login.lbl_Userinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Login_lbl_UserName {
            get {
                return ResourceManager.GetString("Login.lbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login_lbl_UserNamePostfix {
            get {
                return ResourceManager.GetString("Login.lbl_UserNamePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Login_lbl_UserNamePrefix {
            get {
                return ResourceManager.GetString("Login.lbl_UserNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome,.
        /// </summary>
        internal static string Login_lbl_Welcome {
            get {
                return ResourceManager.GetString("Login.lbl_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string Search_lbl_SearchResult {
            get {
                return ResourceManager.GetString("Search.lbl_SearchResult", resourceCulture);
            }
        }
    }
}
