#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AdModel;
using BizModel;

namespace AdModel	
{
	public partial class AdBanner
	{
		private int _adBannerId;
		public virtual int AdBannerId
		{
			get
			{
				return this._adBannerId;
			}
			set
			{
				this._adBannerId = value;
			}
		}
		
		private int _businessEntityId;
		public virtual int BusinessEntityId
		{
			get
			{
				return this._businessEntityId;
			}
			set
			{
				this._businessEntityId = value;
			}
		}
		
		private DateTime _startDate;
		public virtual DateTime StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				this._startDate = value;
			}
		}
		
		private DateTime? _endDate;
		public virtual DateTime? EndDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
		private DateTime _createdDate;
		public virtual DateTime CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private Guid _createdBy;
		public virtual Guid CreatedBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		
		private DateTime? _modifiedDate;
		public virtual DateTime? ModifiedDate
		{
			get
			{
				return this._modifiedDate;
			}
			set
			{
				this._modifiedDate = value;
			}
		}
		
		private Guid? _modifiedBy;
		public virtual Guid? ModifiedBy
		{
			get
			{
				return this._modifiedBy;
			}
			set
			{
				this._modifiedBy = value;
			}
		}
		
		private bool _activeFg;
		public virtual bool ActiveFg
		{
			get
			{
				return this._activeFg;
			}
			set
			{
				this._activeFg = value;
			}
		}
		
		private int _mediaTypeId;
		public virtual int MediaTypeId
		{
			get
			{
				return this._mediaTypeId;
			}
			set
			{
				this._mediaTypeId = value;
			}
		}
		
		private int? _width;
		public virtual int? Width
		{
			get
			{
				return this._width;
			}
			set
			{
				this._width = value;
			}
		}
		
		private int? _height;
		public virtual int? Height
		{
			get
			{
				return this._height;
			}
			set
			{
				this._height = value;
			}
		}
		
		private string _linkURL;
		public virtual string LinkURL
		{
			get
			{
				return this._linkURL;
			}
			set
			{
				this._linkURL = value;
			}
		}
		
		private string _linkTarkget;
		public virtual string LinkTarkget
		{
			get
			{
				return this._linkTarkget;
			}
			set
			{
				this._linkTarkget = value;
			}
		}
		
		private string _linkAltString;
		public virtual string LinkAltString
		{
			get
			{
				return this._linkAltString;
			}
			set
			{
				this._linkAltString = value;
			}
		}
		
		private string _sourcePath;
		public virtual string SourcePath
		{
			get
			{
				return this._sourcePath;
			}
			set
			{
				this._sourcePath = value;
			}
		}
		
		private string _sourceContent;
		public virtual string SourceContent
		{
			get
			{
				return this._sourceContent;
			}
			set
			{
				this._sourceContent = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private int _weight;
		public virtual int Weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				this._weight = value;
			}
		}
		
		private AdMediaType _adMediaType;
		public virtual AdMediaType AdMediaType
		{
			get
			{
				return this._adMediaType;
			}
			set
			{
				this._adMediaType = value;
			}
		}
		
		private BusinessEntity _businessEntity;
		public virtual BusinessEntity BusinessEntity
		{
			get
			{
				return this._businessEntity;
			}
			set
			{
				this._businessEntity = value;
			}
		}
		
		private IList<AdExpose> _adExposes = new List<AdExpose>();
		public virtual IList<AdExpose> AdExposes
		{
			get
			{
				return this._adExposes;
			}
		}
		
		private IList<AdZoneMember> _adZoneMembers = new List<AdZoneMember>();
		public virtual IList<AdZoneMember> AdZoneMembers
		{
			get
			{
				return this._adZoneMembers;
			}
		}
		
	}
}
#pragma warning restore 1591
