#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AdModel;

namespace AdModel	
{
	public partial class AdMediaType
	{
		private int _adMediaTypeId;
		public virtual int AdMediaTypeId
		{
			get
			{
				return this._adMediaTypeId;
			}
			set
			{
				this._adMediaTypeId = value;
			}
		}
		
		private string _mediaTypeName;
		public virtual string MediaTypeName
		{
			get
			{
				return this._mediaTypeName;
			}
			set
			{
				this._mediaTypeName = value;
			}
		}
		
		private IList<AdBanner> _adBanners = new List<AdBanner>();
		public virtual IList<AdBanner> AdBanners
		{
			get
			{
				return this._adBanners;
			}
		}
		
	}
}
#pragma warning restore 1591
