#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace AdModel	
{
	public partial class AdRefSize
	{
		private int _adSizeId;
		public virtual int AdSizeId
		{
			get
			{
				return this._adSizeId;
			}
			set
			{
				this._adSizeId = value;
			}
		}
		
		private string _adSizeName;
		public virtual string AdSizeName
		{
			get
			{
				return this._adSizeName;
			}
			set
			{
				this._adSizeName = value;
			}
		}
		
		private int _height;
		public virtual int Height
		{
			get
			{
				return this._height;
			}
			set
			{
				this._height = value;
			}
		}
		
		private int _width;
		public virtual int Width
		{
			get
			{
				return this._width;
			}
			set
			{
				this._width = value;
			}
		}
		
	}
}
#pragma warning restore 1591
