#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using FormModel;
using EmailModel;

namespace FormModel	
{
	public partial class FormEmail
	{
		private int _formEmailId;
		public virtual int FormEmailId
		{
			get
			{
				return this._formEmailId;
			}
			set
			{
				this._formEmailId = value;
			}
		}
		
		private int _emailEventId;
		public virtual int EmailEventId
		{
			get
			{
				return this._emailEventId;
			}
			set
			{
				this._emailEventId = value;
			}
		}
		
		private string _receipients;
		public virtual string Receipients
		{
			get
			{
				return this._receipients;
			}
			set
			{
				this._receipients = value;
			}
		}
		
		private int _formId;
		public virtual int FormId
		{
			get
			{
				return this._formId;
			}
			set
			{
				this._formId = value;
			}
		}
		
		private int? _emailUDFInfoId;
		public virtual int? EmailUDFInfoId
		{
			get
			{
				return this._emailUDFInfoId;
			}
			set
			{
				this._emailUDFInfoId = value;
			}
		}
		
		private Form _form;
		public virtual Form Form
		{
			get
			{
				return this._form;
			}
			set
			{
				this._form = value;
			}
		}
		
		private EmailEvent _emailEvent;
		public virtual EmailEvent EmailEvent
		{
			get
			{
				return this._emailEvent;
			}
			set
			{
				this._emailEvent = value;
			}
		}
		
	}
}
#pragma warning restore 1591
